default:
  paths:
    features: ../../features
  extensions:
    Behat\MinkExtension\Extension:
      #base_url:  'http://test.localhost/'
      base_url: 'http://192.168.33.10' 
      
      goutte:
        guzzle_parameters:
          request.params:
            redirect.disable: true
      # 
      # switch disable followings if use behat/mink-selenium2-driver 
      #
      #selenium: ~
      #javascript_session: selenium
      # 
      # switch enable followings if use behat/mink-selenium2-driver 
      #
      # javascript_session: selenium2
      # browser_name: 'firefox'
      # selenium2:                    
      #   capabilities: { "browser": "firefox"}
